import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { fetchMentalModels } from '../api/memory';
import { StatusBadge } from '../components/ui/StatusBadge';
import { Compass } from 'lucide-react';

export const MentalModels: React.FC = () => {
  const { data: models, isLoading, isError, error } = useQuery({
    queryKey: ['mental-models'],
    queryFn: fetchMentalModels,
  });

  return (
    <div className="space-y-6 font-mono text-xs">
      <div className="border-b border-edge pb-4">
        <h2 className="text-xl font-bold text-ink flex items-center gap-2">
          <Compass className="w-5 h-5 text-ink-muted" /> Scientific Mental Models
        </h2>
        <p className="text-xs text-ink-muted font-sans mt-0.5">
          High-level institutional knowledge representations generated by Hindsight reflection over experimental evidence.
        </p>
      </div>

      {isLoading ? (
        <div className="p-12 text-center text-ink-faint">Loading mental models...</div>
      ) : isError ? (
        <div className="p-12 text-center text-resona-failure">
          Error loading mental models: {error instanceof Error ? error.message : 'Backend unreachable'}
        </div>
      ) : !models || models.length === 0 ? (
        <div className="p-12 border border-dashed border-edge rounded-lg text-center text-ink-muted">
          No mental models recorded yet.
        </div>
      ) : (
        <div className="space-y-6">
          {models.map((mod) => (
            <div key={mod.id} className="p-6 rounded-lg bg-surface-card border border-edge space-y-4">
              <div className="flex items-start justify-between border-b border-edge pb-3">
                <div>
                  <div className="flex items-center gap-3">
                    <h3 className="text-base font-bold text-ink">{mod.model_name}</h3>
                    <StatusBadge status={mod.status} />
                  </div>
                  <p className="text-xs text-ink-muted font-sans mt-1 leading-relaxed">{mod.description}</p>
                </div>
                <div className="text-right shrink-0">
                  <span className="text-resona-success font-bold block text-sm">{Math.round(mod.confidence * 100)}% Confidence</span>
                  <span className="text-[10px] text-ink-faint">{mod.supporting_experiments_count} Supporting Experiments</span>
                </div>
              </div>

              {mod.directives && mod.directives.length > 0 && (
                <div className="space-y-2">
                  <span className="text-[11px] font-semibold text-ink-muted uppercase tracking-wider block">
                    Distilled Directives:
                  </span>
                  <div className="space-y-2">
                    {mod.directives.map((dir) => (
                      <div key={dir.id} className="p-3 rounded bg-surface border border-edge flex items-center justify-between">
                        <span className="text-xs text-ink font-sans">{dir.directive_text}</span>
                        <StatusBadge status={dir.status} />
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
